
from .self_enhanced_learner_ddpg_double_subtrain import SelfEnhancedDDPGQLearner as SelfEnhancedDDPGQLearnerDoubleSubtrain

REGISTRY={}

REGISTRY["self_enhanced_ddpg_double_subtrain"] =SelfEnhancedDDPGQLearnerDoubleSubtrain
